import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Header from "@/components/Header";
import QueryProvider from "@/components/QueryClientProvider";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import Context from "@/store/context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} overflow-x-hidden`}
        suppressHydrationWarning={true}
      >
        <Context>
          <Toaster richColors />

          <QueryProvider>
            <Header />
            <main className="h-screen">
              {children}
              <Footer />
            </main>
          </QueryProvider>
        </Context>
      </body>
    </html>
  );
}
